var JOURNAL = [
  {"events":["meat","exercise","weekend"],"werewolf":false},
  {"events":["bread","pudding","sleep outside","weekend","touched tree"],"werewolf":false},
  {"events":["meat","nachos","sleep outside","cycling","weekend"],"werewolf":false},
  {"events":["brussel sprouts","ice cream","sleep outside","computer","weekend"],"werewolf":false},
  {"events":["potatoes","candy","sleep outside","exercise","weekend","dentist"],"werewolf":false},
  {"events":["brussel sprouts","pudding","sleep outside","running","weekend"],"werewolf":false},
  {"events":["pizza","sleep outside","computer","work","touched tree"],"werewolf":false},
  {"events":["bread","beer","sleep outside","cycling","work"],"werewolf":false},
  {"events":["cauliflower","sleep outside","work"],"werewolf":false},
  {"events":["pizza","sleep outside","cycling","work"],"werewolf":false},
  {"events":["lasagna","nachos","sleep outside","work"],"werewolf":false},
  {"events":["sleep outside","weekend","touched tree"],"werewolf":false},
  {"events":["lettuce","sleep outside","television","weekend"],"werewolf":false},
  {"events":["spaghetti","sleep outside","work"],"werewolf":false},
  {"events":["sleep outside","computer","work"],"werewolf":false},
  {"events":["lettuce","nachos","sleep outside","work"],"werewolf":false},
  {"events":["meat","sleep outside","running","work"],"werewolf":false},
  {"events":["sleep outside","work"],"werewolf":false},
  {"events":["cauliflower","reading","weekend"],"werewolf":false},
  {"events":["bread","sleep outside","weekend"],"werewolf":false},
  {"events":["lasagna","sleep outside","exercise","work"],"werewolf":false},
  {"events":["spaghetti","sleep outside","reading","work"],"werewolf":false},
  {"events":["meat","ice cream","sleep outside","television","work"],"werewolf":false},
  {"events":["spaghetti","nachos","work"],"werewolf":false},
  {"events":["cauliflower","ice cream","sleep outside","cycling","work"],"werewolf":false},
  {"events":["spaghetti","wolf calls","computer","weekend", "full moon"],"werewolf":true},
  {"events":["potatoes","ice cream","sleep outside","computer","weekend"],"werewolf":false},
  {"events":["potatoes","ice cream","sleep outside","work"],"werewolf":false},
  {"events":["wolf calls","sleep outside","running","work"],"werewolf":false},
  {"events":["potatoes","exercise","work"],"werewolf":false},
  {"events":["pizza","ice cream","computer","work"],"werewolf":false},
  {"events":["lasagna","ice cream","work"],"werewolf":false},
  {"events":["cauliflower","candy","reading","weekend"],"werewolf":false},
  {"events":["lasagna","nachos","sleep outside","running","weekend"],"werewolf":false},
  {"events":["potatoes","sleep outside","work"],"werewolf":false},
  {"events":["meat","work"],"werewolf":false},
  {"events":["pizza","beer","work","dentist"],"werewolf":false},
  {"events":["lasagna","pudding","cycling","work"],"werewolf":false},
  {"events":["spaghetti","sleep outside","reading","work"],"werewolf":false},
  {"events":["spaghetti","pudding","television","weekend"],"werewolf":false},
  {"events":["bread","sleep outside","exercise","weekend"],"werewolf":false},
  {"events":["lasagna","wolf calls","work", "full moon"],"werewolf":true},
  {"events":["pizza","work"],"werewolf":false},
  {"events":["potatoes","exercise","work"],"werewolf":false},
  {"events":["sleep outside","exercise","work"],"werewolf":false},
  {"events":["spaghetti","sleep outside","television","work"],"werewolf":false},
  {"events":["pizza","cycling","weekend"],"werewolf":false},
  {"events":["meat","sleep outside","weekend"],"werewolf":false},
  {"events":["meat","beer","sleep outside","work"],"werewolf":false},
  {"events":["pizza","wolf calls","candy","work", "full moon"],"werewolf":true},
  {"events":["meat","wolf calls","sleep outside","reading","work"],"werewolf":false},
  {"events":["potatoes","wolf calls","sleep outside","work"],"werewolf":false},
  {"events":["meat","nachos","sleep outside","exercise","work"],"werewolf":false},
  {"events":["pizza","wolf calls","sleep outside","television","weekend"],"werewolf":false},
  {"events":["lasagna","sleep outside","cycling","weekend"],"werewolf":false},
  {"events":["cauliflower","wolf calls","sleep outside","computer","work","touched tree"],"werewolf":false},
  {"events":["lettuce","sleep outside","television","work"],"werewolf":false},
  {"events":["potatoes","sleep outside","computer","work"],"werewolf":false},
  {"events":["bread","candy","work"],"werewolf":false},
  {"events":["potatoes","nachos","work"],"werewolf":false},
  {"events":["meat","pudding","sleep outside","weekend"],"werewolf":false},
  {"events":["meat","sleep outside","exercise","weekend","touched tree"],"werewolf":false},
  {"events":["brussel sprouts","running","work"],"werewolf":false},
  {"events":["sleep outside","work"],"werewolf":false},
  {"events":["lettuce","sleep outside","running","work"],"werewolf":false},
  {"events":["candy","sleep outside","work"],"werewolf":false},
  {"events":["brussel sprouts","sleep outside","computer","work"],"werewolf":false},
  {"events":["bread","sleep outside","weekend"],"werewolf":false},
  {"events":["cauliflower","sleep outside","weekend"],"werewolf":false},
  {"events":["spaghetti","candy","television","work","touched tree"],"werewolf":false},
  {"events":["meat","pudding","sleep outside","work"],"werewolf":false},
  {"events":["lettuce","sleep outside","work"],"werewolf":false},
  {"events":["meat","ice cream","sleep outside","cycling","work"],"werewolf":false},
  {"events":["pizza","sleep outside","work"],"werewolf":false},
  {"events":["spaghetti","wolf calls","exercise","full moon"],"werewolf":true},
  {"events":["bread","beer","computer","weekend","touched tree"],"werewolf":false},
  {"events":["sleep outside","running","work"],"werewolf":false},
  {"events":["lettuce","wolf calls","sleep outside","work","touched tree"],"werewolf":false},
  {"events":["lasagna","sleep outside","television","work"],"werewolf":false},
  {"events":["cauliflower","sleep outside","running","work"],"werewolf":false},
  {"events":["meat","sleep outside","running","work"],"werewolf":false},
  {"events":["meat","reading","weekend"],"werewolf":false},
  {"events":["meat","wolf calls","reading","full moon"],"werewolf":true},
  {"events":["potatoes","sleep outside","running","work"],"werewolf":false},
  {"events":["lasagna","ice cream","work","touched tree"],"werewolf":false},
  {"events":["cauliflower","wolf calls","sleep outside","cycling","work"],"werewolf":false},
  {"events":["pizza","sleep outside","running","work"],"werewolf":false},
  {"events":["lettuce","sleep outside","work"],"werewolf":false},
  {"events":["bread","sleep outside","television","weekend"],"werewolf":false},
  {"events":["cauliflower","wolf calls","sleep outside","weekend"],"werewolf":false}
];

// This makes sure the data is exported in node.js —
// `require('./path/to/journal.js')` will get you the array.
if (typeof module != "undefined" && module.exports && (typeof window == "undefined" || window.exports != exports))
  module.exports = JOURNAL;
if (typeof global != "undefined" && !global.JOURNAL)
  global.JOURNAL = JOURNAL;
